name = "anki-challenge"
compatibility_date = "2025-01-21"
compatibility_flags = ["nodejs_compat"]

# Cloudflare Pages sẽ đọc cấu hình build output từ đây.
# Astro mặc định build ra thư mục `dist`.
pages_build_output_dir = "dist"

